### PR TITLE
release version 1.0.0-alpha.2

### PR DESCRIPTION
**Pull request by aidenkeating**
### Motivation

Release `1.0.0-alpha.2`. Naming based on https://semver.org/#spec-item-9. Not sure if we want to do `1.0.0-alpha.1` instead, it seems confusing to me.

@wei-lee Does this look right to you? Following https://github.com/aerogear/aerogear-ios-sdk/blob/master/docs/contrib/release.adoc

### CODE REVIEW

**Comment by aidenkeating** [comment]
@wei-lee Mind taking a look?

**Comment by wei-lee** [comment]
@aidenkeating I think we can use `alpha.1`?

**Comment by wei-lee** [comment]
@danielpassos Not sure I would agree with that. But it probably doesn't matter anyway. @aidenkeating which one you prefer? We do not need to align the SDK versions at the moment.

**Comment by aidenkeating** [comment]
@wei-lee @danielpassos According to semver `1.0.0-alpha < 1.0.0-alpha.1` so I think we should go with `1.0.0-alpha.1` (I do find it confusing though) https://semver.org/#spec-item-11. I'll make a new release branch now.

**Comment by aidenkeating** [comment]
Replaced with https://github.com/aerogear/aerogear-ios-sdk/pull/133

**Pull request closed without merging**
