### PR TITLE
Replace timestamp Int converter to NSString format

### PR DESCRIPTION
**Pull request by danielpassos**
Convert Double in Int to remove the decimal part cause an exception in some cases

> Fatal error: Double value cannot be converted to Int because the result would be greater than Int.max

Related issues: 

* [AGIOS-681](https://issues.jboss.org/browse/AGIOS-681)

### CODE REVIEW

**Comment by wtrocki** [comment]
My vote will be to use long. Timestamp is typically an number.

**Comment by danielpassos** [comment]
@wtrocki I have no problem to use long instead of String. Should I use `CLong` so? Since Swift don't have `Long`?

**Comment by wtrocki** [comment]
Swift has long type but it is still int :)
`UInt64` should work with the parser and also be compatible with the Android and server side validation.

**Comment by danielpassos** [comment]
@wtrocki Done, thanks!

**Pull request merged**
