### PR TITLE
Make configuration immutable

### PR DESCRIPTION
**Pull request by wtrocki**
### Motivation

Change structures to be immutable.

### CODE REVIEW

**Comment by wtrocki** [comment]
Fixing build

**Comment by wei-lee** [comment]
we should make the value immutable wherever possible.

**Comment by wtrocki** [comment]
Fixing build. Going to review code for more cases where we use var.

**Comment by wtrocki** [comment]
Fixed build by removing default value. I verified that using sample app.
Thanks for review.

**Pull request merged**
